import { createContext, Dispatch } from "react";
import { Acao, personagem, salvo } from "./TiposDeObjetos";

let msgsConsoleGeral = Boolean(1);

export const estadoInicial: iVariaveis = {
  msgsConsole: {
    renderizacoes: msgsConsoleGeral && Boolean(0),
    redutor: msgsConsoleGeral && Boolean(0),
    effects: msgsConsoleGeral && Boolean(0),
    roteiro: msgsConsoleGeral && Boolean(0),
    mouseTeclado: msgsConsoleGeral && Boolean(0),
  },
  larguraTela: 640,
  alturaTela: 480,
  telaAtual: "apresentação",
  imagemDeFundoAtual: "",
  audioHabilitado: true,
  volumeGeral: 50,
  musicaAtual: null,
  somParaTocar: null,
  dataDeInicio: 0,
  tempoDeJogo: 0,
  ultimaVezQueCarregou: 0,
  roteiroAtual: -1,
  eventoAtual: -1,
  jogoPausado: false,
  aceitandoInteracao: true,
  exibindoPainelInferior: false,
  personagensNaTelaImg: [],
  personagensNaTela: [],
  personagemParaAdicionar: null,
  personagemParaRemover: null,
  removendoTodosOsPersonagens: false,
  mensagemParaEscrever: "",
  digitandoMensagem: false,
  historicoDeMensagens: [],
  exibindoTelaDeOpcoes: false,
  exibindoTelaDoHistorico: false,
  exibindoTelaDeArquivos: false,
  fonte: "Times New Roman",
  corDaFonte: "#ffffff",
  velocidadeDoTexto: 2,
  arquivoSalvoParaCarregar: null,
  adicionandoPersonagensDoSalvo: false,
};

export interface iVariaveis {
  msgsConsole: {
    renderizacoes: boolean,
    redutor: boolean,
    effects: boolean,
    roteiro: boolean,
    mouseTeclado: boolean,
  },
  larguraTela: number,
  alturaTela: number,
  dataDeInicio: number,
  tempoDeJogo: number,
  ultimaVezQueCarregou: number,
  telaAtual: string,
  roteiroAtual: number,
  eventoAtual: number,
  jogoPausado: boolean,
  aceitandoInteracao: boolean,
  imagemDeFundoAtual: string,
  audioHabilitado: boolean,
  volumeGeral: number,
  musicaAtual: {endereco: string, volume: number} | null,
  somParaTocar: {endereco: string, volume: number} | null,
  personagensNaTela: personagem[],
  personagensNaTelaImg: HTMLImageElement[],
  personagemParaAdicionar: personagem | null,
  personagemParaRemover: string | null,
  removendoTodosOsPersonagens: boolean,
  exibindoPainelInferior: boolean,
  mensagemParaEscrever: string,
  digitandoMensagem: boolean,
  historicoDeMensagens: string[],
  exibindoTelaDeOpcoes: boolean,
  exibindoTelaDoHistorico: boolean,
  exibindoTelaDeArquivos: boolean,
  fonte: string,
  corDaFonte: string,
  velocidadeDoTexto: number,
  arquivoSalvoParaCarregar: salvo | null,
  adicionandoPersonagensDoSalvo: boolean,
}

interface iContexto {
  estado: iVariaveis,
  despachar: Dispatch<Acao>,
  exibirElemento(elem: HTMLElement, tempo?: number, opacFinal?: number): Promise<Animation>,
  ocultarElemento(elem: HTMLElement, tempo?: number): Promise<Animation>,
  voltarParaTelaInicial(): void,
}

export const contexto = createContext<iContexto | null>(null);
